name: store_me
description: "A new Flutter project."

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  bloc: ^8.1.4
  build_runner: ^2.4.11
  cached_network_image: ^3.4.1
  card_loading: ^0.3.2
  connectivity_plus: ^4.0.2
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.4.0
  get_it: ^8.0.2
  go_router: ^14.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  shared_preferences: ^2.3.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/icon/
    - .env

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  android_12:
    image: assets/icon/logo_splash_screen_icon.png
